name: Full Security Scan

on:
  push:
    branches: [ main ]

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  sbom:
    name: SBOM (Anchore)
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json

  zap:
    name: DAST (ZAP Scan)
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://tu-app-en-staging.com'
